### ISSUE TITLE
EOL notice for Enterprise Linux 5

### ISSUE THREAD

**Issue by b-harper** [iuscommunity/announce#4]
Red Hat has issued a [security advisory](https://rhn.redhat.com/errata/RHSA-2016-1990.html) regarding Red Hat Enterprise Linux (RHEL) 5.  Red Hat will be retiring RHEL 5 in six months and IUS will follow suit.  On or shortly after March 31, 2017, IUS will move all  Enterprise Linux (EL) 5 packages into the archive repositories and IUS will no longer support those packages.  See [Red Hat Enterprise Linux Life Cycle](https://access.redhat.com/support/policy/updates/errata/) for more information regarding RHEL's life cycle.

Note, the term Enterprise Linux (EL) refers to Red Hat Enterprise Linux (RHEL) and all of the various forks.  In our case, it refers to both RHEL and CentOS.

**Comment by b-harper** [comment]
Just a reminder, IUS support for EL 5 will end in three months.

**Comment by b-harper** [comment]
Another reminder, IUS support for EL 5 will end in one month.

**Comment by carlwgeorge** [comment]
Two weeks to go!

**Comment by b-harper** [comment]
Just one more week till IUS will drop support for EL 5.

**Comment by b-harper** [comment]
Today is the day.  EL5 has severed us well for 10 years and now it is time to say goodby.   We will give it a few days before moving all EL5 packages into the archive repositories and all the other changes needed to phase out EL5 support.

**Comment by carlwgeorge** [comment]
All EL5 packages have been moved to the archive repositories.

![](http://www.clipartkid.com/images/291/11-rip-tombstone-free-cliparts-that-you-can-download-to-you-computer-b3kRF9-clipart.jpeg)

**Comment by rgm3** [comment]
I tried to disable the ius repo and enable "ius-archive" on my system, but despite the RPMs being in the archive, there is no repomd.xml file available.  Do you plan to run "createrepo" for the archive so that repository metadata is generated and setting enabled=1 in ius-archive.repo works?

**Comment by carlwgeorge** [comment]
Our automation is set up in a way that we can only turn that on or off for an entire OS release, not just the archive directory.  The archive directory is intended to be used as an actual archive, not as a repo.  While an OS is supported we happen to create the repodata in that directory, but we have no interest in continuing to do so after EOL.  Since the content in that directory is not going to change (read: NO MORE UPDATES), you can just download the RPMs you want to install and run `yum localinstall` on them.  You could also copy that entire directory to a server you control, run createrepo on it, and host it yourself.  Again, it isn't going to change, so you just have to copy it once.

But seriously, please update to EL6 or EL7.

**Comment by rgm3** [comment]
Thanks, updates are underway.  I only bought it up because it seemed to me like `/etc/yum.repos.d/ius-archive.repo` was a way to install some IUS packages on EL5 after EOL.  But I understand now that it was never intended to be that, but more likely a way to allow folks to downgrade a package if they needed to before the EOL had happened.

**Comment by carlwgeorge** [comment]
> a way to allow folks to downgrade a package if they needed to before the EOL had happened.

Exactly that.  We typically only keep the absolute latest version of RPMs in our stable repo, so if you discover that the latest RPM broke something for you, you could quickly downgrade (pass `--enablerepo ius-archive` to your yum command) without waiting on action from us.

**Comment by chasersrush** [comment]
Thank you, that's very fine and dandy,

But, there is no reason to throw a monkey wrench in the archived repository, by not including the repodata, because the end-of-life of EL5. It's just a cruel, vindictive and totally uncalled for action.

Look how the people of Centos.org themselves, have archived the repository for Centos 5,  without disabling the repodata used by yum. If they can provide a repository which includes the repodata, why can you guys not?

[C5.11-base]
name=CentOS-5.11 - Base
baseurl=http://vault.centos.org/5.11/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

There are others, like rpms.famillecollet.com (remi), webtatic.com, rpmfusion.org, etc. that not only keep fully functioning archives, but have produced some needed updated packages.

Just because I am still using an old car, so to speak (centos 5), doesn't mean you guys have to puncture the tires, in order to try to force me to upgrade to latest version. I am fully aware that there is Centos 7, but personally along with many other users we can not upgrade to the latest versions, for many valid reasons. 

In my case, Centos 5 is running an such and old machine, with so many extraneous packages installed, that it would brake the production server for weeks, while trying to fix the dependencies nightmare that will suredly unfold. To put it simple, I can not upgrade until the boses that own my job, decide to buy a new machine, to install Centos 7 from scratch, and then, methodically transfer and debug, the functioning programs, while still maintaining the production server up.

So, please guys,  don't be so stinky, and (please) generate the darn repodata.

Thank you

**Comment by b-harper** [comment]
We underestimated the number of people that want to continue to use EL5.   The repodata has been put back into place.  

That being said, we must stress that Red Hat no loner supports EL5 and will not release any security patches.  If you are still running EL5, upgrade **NOW**!
